package com.dyz.myBatis.dao;

import java.util.List;

import com.dyz.gameserver.pojo.Account;

public interface AccountMapper {
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was genqqerated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    Account selectByPrimaryKey(Integer id);
    
    //通过openid查询用户
    Account selectAccount(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Account record);
    /**
     * 获取最大的id值
     * @return int
     */
    int selectMaxId();
    /**
     * 获取所有玩家
     * @return
     */
    List<Account> selectAllAccounts();
    
    
    /**
     * 获取排行榜
     * @return
     */
    List<Account> selectTopAccounts();
    
    /**
     * 修改人气
     */
    void updateCharmnun();
    /**
     * 昨日人气
     * @return
     */
    List<Account> selectYesterdayCharmnumTopAccounts();
    
    /**
     * 今日人气
     * @return
     */
    List<Account> selectToDayCharmnumTopAccounts();
    
    /**
     * 保存邀请码
     * @param account
     * @return
     */
    int updateInviteCode(Account account);
    
    
}